# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      - uses: GuillaumeFalourd/create-other-repo-branch-action@v1
        with:
          repository_owner: GHAPITesting
          repository_name: python-demo
          new_branch_name: python-action
          new_branch_ref: main
          access_token: ${{ secrets.ACCESS_TOKEN}}
